# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

twilio_sid: AC695b8678b84a7bb3fed825123d9020ac
twilio_token: 2d1cc9fe62f591367d44b5bebd9d0cc9
twilio_service_sid: MGce4a1698923eefa764d6698b49de783d
twilio_number: (917)336-5920
